# Site settings
name: Home Sweet Chaos
email: skylindiane@gmail.com
url: 
description: "Lifestyle blog about chaos of family life with kids."
author: "Skylin"
title: "Home Sweet Chaos Blog"
permalink: pretty
baseurl: /jekyll-theme-blogfolio

# social
github:
  username: homesweetchaos
